services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - '27000:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
